In [2]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('/home/aditya/Documents/100DayofMLcode/Datasets/Day1.csv')

In [23]:
df

Name Sex   Age  Height (in)  Weight (lbs)
0   Alex   M  41.0          NaN         170.0
1   Bert   M  42.0         68.0         166.0
2   Carl   M  32.0         70.0         155.0
3   Dave   M  39.0         72.0         167.0
4   Elly   F  30.0         66.0         124.0
5   Fran   F  33.0         66.0         115.0
6   Gwen   F  26.0         64.0         121.0
7   Hank   M  30.0         71.0           NaN
8   Ivan   M  53.0         72.0         175.0
9   Jake   M  32.0         69.0         143.0
10  Kate   F  47.0         69.0         139.0
11  Luke   M  34.0         72.0         163.0
12  Myra   F  23.0         62.0          98.0
13  Neil   M  36.0         75.0         160.0
14  Omar   M   NaN         70.0         145.0
15  Page   F  31.0         67.0         135.0
16  Quin   M  29.0         71.0         176.0
17  Ruth   F  28.0         65.0         131.0

In [30]:
Y = df['Sex'].values
X = df.drop(['Sex'], axis=1).values

In [31]:
print(X)
print(Y)

[['Alex' 41.0 nan 170.0]
 ['Bert' 42.0 68.0 166.0]
 ['Carl' 32.0 70.0 155.0]
 ['Dave' 39.0 72.0 167.0]
 ['Elly' 30.0 66.0 124.0]
 ['Fran' 33.0 66.0 115.0]
 ['Gwen' 26.0 64.0 121.0]
 ['Hank' 30.0 71.0 nan]
 ['Ivan' 53.0 72.0 175.0]
 ['Jake' 32.0 69.0 143.0]
 ['Kate' 47.0 69.0 139.0]
 ['Luke' 34.0 72.0 163.0]
 ['Myra' 23.0 62.0 98.0]
 ['Neil' 36.0 75.0 160.0]
 ['Omar' nan 70.0 145.0]
 ['Page' 31.0 67.0 135.0]
 ['Quin' 29.0 71.0 176.0]
 ['Ruth' 28.0 65.0 131.0]]
['M' 'M' 'M' 'M' 'F' 'F' 'F' 'M' 'M' 'M' 'F' 'M' 'F' 'M' 'M' 'F' 'M' 'F']


In [34]:
from sklearn.impute import SimpleImputer as imputer
Imputer = imputer(missing_values = np.nan, strategy = "mean", verbose = 0)
Imputer = Imputer.fit(X[ : , 1:4])
X[ : , 1:4] = Imputer.transform(X[ : , 1:4])

In [35]:
X

array([['Alex', 41.0, 68.76470588235294, 170.0],
       ['Bert', 42.0, 68.0, 166.0],
       ['Carl', 32.0, 70.0, 155.0],
       ['Dave', 39.0, 72.0, 167.0],
       ['Elly', 30.0, 66.0, 124.0],
       ['Fran', 33.0, 66.0, 115.0],
       ['Gwen', 26.0, 64.0, 121.0],
       ['Hank', 30.0, 71.0, 146.05882352941177],
       ['Ivan', 53.0, 72.0, 175.0],
       ['Jake', 32.0, 69.0, 143.0],
       ['Kate', 47.0, 69.0, 139.0],
       ['Luke', 34.0, 72.0, 163.0],
       ['Myra', 23.0, 62.0, 98.0],
       ['Neil', 36.0, 75.0, 160.0],
       ['Omar', 34.470588235294116, 70.0, 145.0],
       ['Page', 31.0, 67.0, 135.0],
       ['Quin', 29.0, 71.0, 176.0],
       ['Ruth', 28.0, 65.0, 131.0]], dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

In [37]:
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)

In [38]:
X

array([[0, 41.0, 68.76470588235294, 170.0],
       [1, 42.0, 68.0, 166.0],
       [2, 32.0, 70.0, 155.0],
       [3, 39.0, 72.0, 167.0],
       [4, 30.0, 66.0, 124.0],
       [5, 33.0, 66.0, 115.0],
       [6, 26.0, 64.0, 121.0],
       [7, 30.0, 71.0, 146.05882352941177],
       [8, 53.0, 72.0, 175.0],
       [9, 32.0, 69.0, 143.0],
       [10, 47.0, 69.0, 139.0],
       [11, 34.0, 72.0, 163.0],
       [12, 23.0, 62.0, 98.0],
       [13, 36.0, 75.0, 160.0],
       [14, 34.470588235294116, 70.0, 145.0],
       [15, 31.0, 67.0, 135.0],
       [16, 29.0, 71.0, 176.0],
       [17, 28.0, 65.0, 131.0]], dtype=object)

In [39]:
Y

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0])

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

In [41]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [42]:
X_train

array([[ 0.89350016,  0.48925128,  0.33141754,  0.00640064],
       [-0.946059  , -0.52747403, -0.88676586, -0.96300496],
       [-1.31397083, -0.07262324,  0.33141754,  0.46802235],
       [ 1.26141199, -0.75489943,  0.63596339,  1.43742794],
       [ 1.44536791, -0.98232483, -1.19131171, -0.63986976],
       [-0.02627942, -0.07262324,  0.02687169, -0.08592371],
       [-0.39419125, -0.52747403,  0.63596339,  0.05527823],
       [ 0.70954425,  0.83707836,  1.85414679,  0.6988332 ],
       [ 0.34163242,  0.38222756,  0.94050924,  0.83731972],
       [-1.13001491,  1.51935455,  0.94050924,  1.0219684 ],
       [-1.68188266,  1.97420535, -0.04478615,  1.16045491],
       [-0.76210308,  0.15480216, -0.88676586, -1.3784645 ],
       [ 1.07745608, -0.30004863, -0.58222001, -0.45522107],
       [ 0.52558833, -2.11945182, -2.10494926, -2.1632214 ]])

In [43]:
X_test

array([[-1.56961369,  0.        , -0.08737041,  0.73379939],
       [-0.07474351, -1.59601494, -1.4852969 , -1.36277029],
       [ 0.52320456,  1.09726027,  1.31055608,  1.15311332],
       [ 1.12115264,  0.49875467,  0.26211122, -0.52414242]])