Importing necessary Libraries

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [62]:
df = pd.read_csv('/home/aditya/Documents/100DayofMLcode/Datasets/Day3.csv')

In [63]:
df

Sex  Weight (lbs, Sep)  Weight (lbs, Apr)  BMI (Sep)  BMI (Apr)
0    M                159                130      22.02      18.14
1    M                214                190      19.70      17.44
2    M                163                152      24.09      22.43
3    M                205                194      26.97      25.57
4    F                150                141      21.51      20.10
..  ..                ...                ...        ...        ...
62   M                143                156      22.51      24.45
63   M                165                181      23.69      25.80
64   F                 93                108      15.08      17.74
65   M                163                181      22.64      25.33
66   M                207                231      36.57      40.86

[67 rows x 5 columns]

In [64]:
Y = df['Sex'].values

In [65]:
X = df.iloc[:,1:].values

Label Encoding

In [66]:
label = LabelEncoder()

In [67]:
Y = label.fit_transform(Y)

In [68]:
print(Y)

[1 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0
 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1]


In [69]:
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

Normalization

In [70]:
SX = StandardScaler()
X_train = SX.fit_transform(X_train)
X_test = SX.fit_transform(X_test)

In [71]:
print(X_train)

[[ 2.09578581e-01 -2.04719611e-01 -1.66063101e-01 -6.22524031e-01]
 [-2.04605530e-01 -5.45446714e-02 -5.50972466e-02  9.40370145e-02]
 [-1.29299328e-01  1.33174003e-01 -1.04210932e+00 -6.94446515e-01]
 [ 6.99068895e-01  2.08261473e-01  5.87336649e-01 -1.85963097e-03]
 [ 4.35497188e-01  2.08261473e-01  7.27504045e-01  3.76399359e-01]
 [-8.82361349e-01 -5.42613225e-01 -1.28101098e-01  3.65744177e-01]
 [-1.29654546e+00 -1.59383780e+00 -1.29908288e+00 -1.47760245e+00]
 [ 2.09578581e-01  2.08261473e-01  1.98956158e-01  2.00588843e-01]
 [ 6.99068895e-01  1.29702978e+00  1.63914309e-01  7.70641124e-01]
 [-8.82361349e-01 -6.92788165e-01 -1.42150896e-02  2.61856144e-01]
 [ 1.18855921e+00  1.29702978e+00  1.79066052e-02  3.54335089e-02]
 [-8.07055147e-01 -1.10576925e+00 -2.47827415e-01 -5.87894687e-01]
 [ 3.60190986e-01  1.33174003e-01  1.52470611e+00  1.14357252e+00]
 [ 3.60190986e-01  3.58436412e-01 -3.26671575e-01 -2.97540954e-01]
 [-8.07055147e-01 -7.67875634e-01 -6.71249756e-01 -5.87894687e

Training

In [72]:
reg = LinearRegression()
reg = reg.fit(X_train, Y_train)

In [73]:
Y_pred = reg.predict(X_test)
X_pred = reg.predict(X_train)